//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class drawing
    {
        public int id { get; set; }
        public string name { get; set; }
        public int shapeId { get; set; }
        public int userId { get; set; }
        public string displayDrawingUrl { get; set; }
        public string drawingUrl { get; set; }
        public bool isPublished { get; set; }
    
        public virtual shape shape { get; set; }
        public virtual user user { get; set; }
    }
}
